/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.forms;

import com.sv.udb.Clases.CSVManej;
import com.sv.udb.Clases.Gasolinera;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis
 */
public class FrmGasolinera extends javax.swing.JFrame {

    /**
     * Creates new form FrmGasolinera
     */
   
    Gasolinera obj = new Gasolinera();
    double tipo,cantidad ;
   List<Gasolinera> Actual;
   DecimalFormat df = new DecimalFormat("#.##");
    public FrmGasolinera() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Damos la cantidad que hay en existencia
        obj.setDispo1(1000);
        obj.setDispo2(1000);
        obj.setDispo3(1000);
       double i1,i2,i3;
    i1 = Double.parseDouble(df.format((obj.getDispo1()*100)/1000));
     i2 = Double.parseDouble(df.format((obj.getDispo2()*100)/1000));
      i3 = Double.parseDouble(df.format((obj.getDispo2()*100)/1000));
     lblContainerN1.setText(i1+"%");
         lblContainerN2.setText(i2+"%");
          lblContainerN3.setText(i3+"%");
        tipo=0;
       btnPagar.setEnabled(false);
       btnMostrar.enable(false);
    }
 private void problarData()
    {
        
        this.tblTodo.getTableHeader().setUI(null); //Quitar título de la columna
        //Cambiar color de selección
        this.tblTodo.setSelectionBackground(new Color(255, 255, 204));
        this.tblTodo.setSelectionForeground(Color.BLACK);
        
        DefaultTableModel model = (DefaultTableModel)this.tblTodo.getModel();
        while(model.getRowCount()>0){model.removeRow(0);} //Limpiar modelo

        //Obtenes y cargar la data CSV
       CSVManej obje = new CSVManej();
        Actual = new ArrayList<>();
        this.Actual = obje.getData();
        for(Gasolinera temp : obje.getData())
        {
            String text = String.format("<html><div style='display:table'><div><div><strong> %s</strong> "
                + "</div></div><div style='color:gray'>%s</div></div></html>", 
                    temp.getCantidad(), temp.getNombre());
            model.addRow(new Object[]{text, temp.getPago()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegular1 = new javax.swing.JLabel();
        lblContainerOne2 = new javax.swing.JLabel();
        jpbPrincipal = new javax.swing.JPanel();
        lblDiesel = new javax.swing.JLabel();
        lblRegular = new javax.swing.JLabel();
        lblEspecial = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jrdDinero = new javax.swing.JRadioButton();
        jrdGalones = new javax.swing.JRadioButton();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        btnGetGasoline = new javax.swing.JButton();
        lblTipo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPago = new javax.swing.JLabel();
        lblPagoD = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        lblVuelto = new javax.swing.JLabel();
        lblVueltoD = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPagadoD = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblGalonesC = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblContainerOne = new javax.swing.JLabel();
        lblContainerThree = new javax.swing.JLabel();
        lblContainerTwo = new javax.swing.JLabel();
        lblContainerN1 = new javax.swing.JLabel();
        lblContainerN2 = new javax.swing.JLabel();
        lblContainerN3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTodo = new javax.swing.JTable();

        lblRegular1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblRegular1.setText("Regular");

        lblContainerOne2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sv/udb/img/container.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guia03_POO1 //// Luis Chévez");

        jpbPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Gasolinera El Petrolito"));

        lblDiesel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblDiesel.setText("Diesel");
        lblDiesel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDieselMouseClicked(evt);
            }
        });

        lblRegular.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblRegular.setText("Regular");
        lblRegular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegularMouseClicked(evt);
            }
        });

        lblEspecial.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblEspecial.setText("Especial");
        lblEspecial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEspecialMouseClicked(evt);
            }
        });

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jrdDinero.setText("Dinero $");
        jrdDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdDineroActionPerformed(evt);
            }
        });

        jrdGalones.setText("Cantidad Galones");
        jrdGalones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdGalonesActionPerformed(evt);
            }
        });

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        lblNombre.setText("Nombre del cliente:");

        lblCantidad.setText("Cantidad:");

        btnGetGasoline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sv/udb/img/gasoline.png"))); // NOI18N
        btnGetGasoline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetGasolineActionPerformed(evt);
            }
        });

        lblTipo.setText("Seleccione el tipo ");

        javax.swing.GroupLayout jpbPrincipalLayout = new javax.swing.GroupLayout(jpbPrincipal);
        jpbPrincipal.setLayout(jpbPrincipalLayout);
        jpbPrincipalLayout.setHorizontalGroup(
            jpbPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpbPrincipalLayout.createSequentialGroup()
                .addGroup(jpbPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantidad)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo)
                    .addGroup(jpbPrincipalLayout.createSequentialGroup()
                        .addComponent(jrdDinero)
                        .addGap(18, 18, 18)
                        .addComponent(jrdGalones))
                    .addComponent(lblNombre)
                    .addGroup(jpbPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDiesel)
                        .addGap(42, 42, 42)
                        .addComponent(lblRegular)
                        .addGap(18, 18, 18)
                        .addComponent(lblEspecial))
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpbPrincipalLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnGetGasoline)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpbPrincipalLayout.setVerticalGroup(
            jpbPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpbPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpbPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecial)
                    .addComponent(lblRegular)
                    .addComponent(lblDiesel))
                .addGap(18, 18, 18)
                .addComponent(lblTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpbPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrdDinero)
                    .addComponent(jrdGalones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGetGasoline, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));

        lblPago.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblPago.setText("Total:");

        lblPagoD.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblPagoD.setText("$0");

        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sv/udb/img/pay.png"))); // NOI18N
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        lblVuelto.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblVuelto.setText("Vuelto:");

        lblVueltoD.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblVueltoD.setText("$0");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Pagado:");

        lblPagadoD.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblPagadoD.setText("$0");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Galones:");

        lblGalonesC.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblGalonesC.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGalonesC))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVuelto)
                                    .addComponent(jLabel2))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVueltoD)
                                    .addComponent(lblPagadoD)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPagoD)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblGalonesC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPago))
                    .addComponent(lblPagoD, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPagadoD)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVuelto)
                    .addComponent(lblVueltoD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Existencias"));

        lblContainerOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sv/udb/img/container.png"))); // NOI18N

        lblContainerThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sv/udb/img/container.png"))); // NOI18N

        lblContainerTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sv/udb/img/container.png"))); // NOI18N

        lblContainerN1.setText("jLabel4");

        lblContainerN2.setText("jLabel5");

        lblContainerN3.setText("jLabel6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblContainerOne))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblContainerN1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblContainerN2))
                    .addComponent(lblContainerTwo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContainerThree)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblContainerN3)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblContainerThree, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(lblContainerTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblContainerOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContainerN1)
                    .addComponent(lblContainerN2)
                    .addComponent(lblContainerN3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        tblTodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTodo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMostrar)
                .addGap(197, 197, 197))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnMostrar)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpbPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpbPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrdDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdDineroActionPerformed
    jrdGalones.setSelected(false);
    }//GEN-LAST:event_jrdDineroActionPerformed

    private void btnGetGasolineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetGasolineActionPerformed
     double indi=0,val=0;
    if(!(txtCantidad.getText().trim().isEmpty())  && !(txtNombre.getText().trim().isEmpty()) && tipo != 0&& (jrdDinero.isSelected() == true || jrdGalones.isSelected() == true))
    {
     if(tipo == 1)
    {
    indi = obj.getDispo1();
    val = obj.getPrec1();
    }
     if(tipo == 2)
    {
   indi = obj.getDispo2();
   val = obj.getPrec2();
    }
      if(tipo == 3)
    {
   indi = obj.getDispo2();
   val = obj.getPrec3();
    }
   
    try 
    {
    cantidad = Double.parseDouble(txtCantidad.getText());
    obj.setNombre(txtNombre.getText());
    if(jrdDinero.isSelected() == true)
    {
    if(indi >= (cantidad / val))
    {
    
    obj.ventaDinero(cantidad, tipo);
     lblGalonesC.setText(obj.getCantidad()+"");
       btnPagar.setEnabled(true);
    btnGetGasoline.setEnabled(false);
    lblPagoD.setText("$"+txtCantidad.getText());
    obj.setPago(Double.parseDouble(txtCantidad.getText()));
    double i1,i2,i3;
    
    i1 = Double.parseDouble(df.format((obj.getDispo1()*100)/1000));
     i2 = Double.parseDouble(df.format((obj.getDispo2()*100)/1000));
      i3 = Double.parseDouble(df.format((obj.getDispo3()*100)/1000));
     lblContainerN1.setText(i1+"%");
         lblContainerN2.setText(i2+"%");
          lblContainerN3.setText(i3+"%");
   
    }
    else
    {
    JOptionPane.showMessageDialog(this,"La bomba ya no posee gasolina suficiente");
    txtCantidad.setText("");
      txtCantidad.requestFocus();
    }
    }
    else if (jrdGalones.isSelected() == true)
    {
    if (indi >= Double.parseDouble(txtCantidad.getText()))
    {
    obj.ventaGalones(cantidad, tipo);
    JOptionPane.showMessageDialog(this, "$"+obj.getPago());
    lblPagoD.setText("$"+obj.getPago());
    btnPagar.setEnabled(true);
    btnGetGasoline.setEnabled(false);
    lblGalonesC.setText(txtCantidad.getText());
    double i1,i2,i3;
    
    i1 =Double.parseDouble(df.format((obj.getDispo1()*100)/1000));
     i2 = Double.parseDouble(df.format((obj.getDispo2()*100)/1000));
      i3 = Double.parseDouble(df.format((obj.getDispo3()*100)/1000));
     lblContainerN1.setText(i1+"%");
         lblContainerN2.setText(i2+"%");
          lblContainerN3.setText(i3+"%");
    }
    else
    {
    JOptionPane.showMessageDialog(this,"La bomba ya no posee gasolina suficiente");
    txtCantidad.setText("");
      txtCantidad.requestFocus();
    }
    } 
    } catch (Exception e) 
    {
    JOptionPane.showMessageDialog(this, "Solo ingrese numeros");
    txtCantidad.setText("");
    txtCantidad.requestFocus();
    }
    }
    else
    {
    JOptionPane.showMessageDialog(this, "Llene todos los datos o no hay gas suficiente");
    }
        System.out.println(obj.getCantidad());
        System.out.println(obj.getNombre());
        System.out.println(obj.getPago());
        System.out.println(obj.getTipo());
        this.Actual = new ArrayList<>();
     Actual.add(obj);
    CSVManej obj2 = new CSVManej();
    obj2.Save(Actual);
    }//GEN-LAST:event_btnGetGasolineActionPerformed

    private void jrdGalonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdGalonesActionPerformed
    jrdDinero.setSelected(false);
    }//GEN-LAST:event_jrdGalonesActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
    char c = evt.getKeyChar() ;
    if (Character.isDigit(c));
    else if (Character.isISOControl(c));
    else if (Character.isSpaceChar(c));
    else if (c == '.' && !(txtCantidad.getText().contains(".")));
    else
    {
    evt.consume();
    }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
     char c = evt.getKeyChar() ;
    if (Character.isLetter(c));
    else if (Character.isISOControl(c));
    else if (Character.isSpaceChar(c));
    else
    {
    evt.consume();
    }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void lblDieselMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDieselMouseClicked
    tipo = 1;
  lblDiesel.setForeground(Color.yellow);
  lblRegular.setForeground(Color.black);
  lblEspecial.setForeground(Color.black);
    }//GEN-LAST:event_lblDieselMouseClicked

    private void lblRegularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegularMouseClicked
    tipo = 2;
  lblRegular.setForeground(Color.yellow);
  lblDiesel.setForeground(Color.black);
  lblEspecial.setForeground(Color.black);
    }//GEN-LAST:event_lblRegularMouseClicked

    private void lblEspecialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEspecialMouseClicked
    tipo = 3;
    lblEspecial.setForeground(Color.yellow);
    lblRegular.setForeground(Color.black);
    lblDiesel.setForeground(Color.black);
   
    }//GEN-LAST:event_lblEspecialMouseClicked

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
  
   try 
   {
   double cuenta= Double.parseDouble(JOptionPane.showInputDialog("Ingrese la cantidad pagada"));
   lblPagadoD.setText("$"+cuenta);
   if(!(cuenta == obj.getPago()))
   {
   if(cuenta >= obj.getPago())
   {
   cuenta = cuenta - obj.getPago();
   JOptionPane.showMessageDialog(this, "Su vuelto es:"+cuenta);
     lblVueltoD.setText("$"+cuenta);
     btnGetGasoline.setEnabled(true);
     btnPagar.setEnabled(false);
     mthLimpiar();
     
   }
   else
   {
   JOptionPane.showMessageDialog(this,"El pago tiene que ser mayor o igual a la deuda" );
   }
   }
   else
   {
     btnGetGasoline.setEnabled(true);
     btnPagar.setEnabled(false);
     mthLimpiar();
   }
   }
   catch (Exception e) 
   {
   JOptionPane.showMessageDialog(this, "Solo ingrese numeros");
   }
     
   
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
    problarData();
    }//GEN-LAST:event_btnMostrarActionPerformed
    public void mthLimpiar()
    {
    txtCantidad.setText("");
    txtNombre.setText("");
    jrdDinero.setSelected(false);
    jrdGalones.setSelected(false);
    lblDiesel.setForeground(Color.black);
    lblRegular.setForeground(Color.black);
    lblEspecial.setForeground(Color.black);
    lblPagoD.setText("$0");
    lblPagadoD.setText("$0");
    lblVueltoD.setText("$0");
    lblGalonesC.setText("0");
    tipo = 0;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGasolinera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetGasoline;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpbPrincipal;
    private javax.swing.JRadioButton jrdDinero;
    private javax.swing.JRadioButton jrdGalones;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblContainerN1;
    private javax.swing.JLabel lblContainerN2;
    private javax.swing.JLabel lblContainerN3;
    private javax.swing.JLabel lblContainerOne;
    private javax.swing.JLabel lblContainerOne2;
    private javax.swing.JLabel lblContainerThree;
    private javax.swing.JLabel lblContainerTwo;
    private javax.swing.JLabel lblDiesel;
    private javax.swing.JLabel lblEspecial;
    private javax.swing.JLabel lblGalonesC;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPagadoD;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblPagoD;
    private javax.swing.JLabel lblRegular;
    private javax.swing.JLabel lblRegular1;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblVuelto;
    private javax.swing.JLabel lblVueltoD;
    private javax.swing.JTable tblTodo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
