/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.forms;

import com.sv.udb.Clases.Gasolinera;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class FrmGasolinera extends javax.swing.JFrame {

    /**
     * Creates new form FrmGasolinera
     */
    Gasolinera obj = new Gasolinera();
    double tipo,cantidad ;
    public FrmGasolinera() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Damos la cantidad que hay en existencia
        obj.setDispo1(1000);
        obj.setDispo2(1000);
        obj.setDispo3(1000);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegular1 = new javax.swing.JLabel();
        jpbPrincipal = new javax.swing.JPanel();
        lblDiesel = new javax.swing.JLabel();
        lblRegular = new javax.swing.JLabel();
        lblEspecial = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jrdDinero = new javax.swing.JRadioButton();
        jrdGalones = new javax.swing.JRadioButton();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        btnGetGasoline = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        lblRegular1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblRegular1.setText("Regular");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guia03_POO1 //// Luis Chévez");

        jpbPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Gasolinera El Petrolito"));

        lblDiesel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblDiesel.setText("Diesel");
        lblDiesel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDieselMouseClicked(evt);
            }
        });

        lblRegular.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblRegular.setText("Regular");
        lblRegular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegularMouseClicked(evt);
            }
        });

        lblEspecial.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblEspecial.setText("Especial");
        lblEspecial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEspecialMouseClicked(evt);
            }
        });

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jrdDinero.setText("Dinero $");
        jrdDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdDineroActionPerformed(evt);
            }
        });

        jrdGalones.setText("Cantidad Galones");
        jrdGalones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdGalonesActionPerformed(evt);
            }
        });

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        lblNombre.setText("Nombre del cliente:");

        lblCantidad.setText("Cantidad:");

        btnGetGasoline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sv/udb/img/gasoline.png"))); // NOI18N
        btnGetGasoline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetGasolineActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione el tipo ");

        javax.swing.GroupLayout jpbPrincipalLayout = new javax.swing.GroupLayout(jpbPrincipal);
        jpbPrincipal.setLayout(jpbPrincipalLayout);
        jpbPrincipalLayout.setHorizontalGroup(
            jpbPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpbPrincipalLayout.createSequentialGroup()
                .addGroup(jpbPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantidad)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jpbPrincipalLayout.createSequentialGroup()
                        .addComponent(jrdDinero)
                        .addGap(18, 18, 18)
                        .addComponent(jrdGalones))
                    .addComponent(lblNombre)
                    .addGroup(jpbPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDiesel)
                        .addGap(33, 33, 33)
                        .addComponent(lblRegular)
                        .addGap(27, 27, 27)
                        .addComponent(lblEspecial))
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpbPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGetGasoline)
                .addGap(83, 83, 83))
        );
        jpbPrincipalLayout.setVerticalGroup(
            jpbPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpbPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpbPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiesel)
                    .addComponent(lblRegular)
                    .addComponent(lblEspecial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpbPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrdGalones)
                    .addComponent(jrdDinero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGetGasoline, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpbPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpbPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrdDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdDineroActionPerformed
    jrdGalones.setSelected(false);
    }//GEN-LAST:event_jrdDineroActionPerformed

    private void btnGetGasolineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetGasolineActionPerformed
    obj.ventaDinero(cantidad, tipo);
    }//GEN-LAST:event_btnGetGasolineActionPerformed

    private void jrdGalonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdGalonesActionPerformed
    jrdDinero.setSelected(false);
    }//GEN-LAST:event_jrdGalonesActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
    char c = evt.getKeyChar() ;
    if (Character.isDigit(c));
    else if (Character.isISOControl(c));
    else if (Character.isSpaceChar(c));
    else if (c == '.' && !(txtCantidad.getText().contains(".")));
    else
    {
    evt.consume();
    }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
     char c = evt.getKeyChar() ;
    if (Character.isLetter(c));
    else if (Character.isISOControl(c));
    else if (Character.isSpaceChar(c));
    else
    {
    evt.consume();
    }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void lblDieselMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDieselMouseClicked
    tipo = 1;
    }//GEN-LAST:event_lblDieselMouseClicked

    private void lblRegularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegularMouseClicked
    tipo = 2;
    }//GEN-LAST:event_lblRegularMouseClicked

    private void lblEspecialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEspecialMouseClicked
    tipo = 3;
    }//GEN-LAST:event_lblEspecialMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGasolinera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetGasoline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpbPrincipal;
    private javax.swing.JRadioButton jrdDinero;
    private javax.swing.JRadioButton jrdGalones;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDiesel;
    private javax.swing.JLabel lblEspecial;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegular;
    private javax.swing.JLabel lblRegular1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
